name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global pull.rebase false
      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Try to pull first
          git remote add hf https://product-ai-gl:$HF_TOKEN@huggingface.co/spaces/product-ai-gl/mentor-ama-review
          git fetch hf main || true
          git merge hf/main --allow-unrelated-histories || true
          # Force push to HF Hub
          git push -f hf main